CREATE TABLE orgs ( id          TEXT PRIMARY KEY, name        TEXT NOT NULL, status      TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'suspended', 'rejected', 'demo')), signup_email  TEXT, signup_domain TEXT, created_at    INTEGER NOT NULL, approved_at   INTEGER, note          TEXT );
CREATE INDEX idx_orgs_status ON orgs(status, created_at DESC);
INSERT INTO orgs (id, name, status, created_at, approved_at) VALUES ('org-demo', 'Studierendenwerk (Demo)', 'demo', 0, 0);
ALTER TABLE buildings ADD COLUMN org_id TEXT REFERENCES orgs;
ALTER TABLE staff     ADD COLUMN org_id TEXT REFERENCES orgs;
ALTER TABLE tenants   ADD COLUMN org_id TEXT REFERENCES orgs;
UPDATE buildings SET org_id = 'org-demo' WHERE org_id IS NULL;
UPDATE staff     SET org_id = 'org-demo' WHERE org_id IS NULL;
UPDATE tenants   SET org_id = 'org-demo' WHERE org_id IS NULL;
CREATE INDEX idx_buildings_org ON buildings(org_id);
CREATE INDEX idx_staff_org ON staff(org_id);
CREATE INDEX idx_tenants_org ON tenants(org_id);
ALTER TABLE staff ADD COLUMN is_platform_admin INTEGER NOT NULL DEFAULT 0;
DROP VIEW IF EXISTS v_ticket_location;
CREATE VIEW v_ticket_location AS SELECT t.id AS ticket_id, t.state, t.reported_at, t.closed_at, t.cause, o.id AS object_id, o.object_type, o.riser, o.ordinal, r.id AS room_id, r.code AS room_code, r.room_type, r.kind AS room_kind, r.label AS room_label, u.id AS unit_id, u.code AS unit_code, u.floor, u.kind AS unit_kind, u.is_common, b.id AS building_id, COALESCE(b.display_code, b.code) AS building_code, b.name AS building_name, b.org_id AS org_id FROM tickets t JOIN objects   o ON o.id = t.object_id JOIN rooms     r ON r.id = o.room_id JOIN units     u ON u.id = r.unit_id JOIN buildings b ON b.id = u.building_id;
ALTER TABLE notifications ADD COLUMN org_id TEXT REFERENCES orgs;
UPDATE notifications SET org_id = 'org-demo' WHERE org_id IS NULL;
CREATE INDEX idx_notif_org ON notifications(org_id, created_at DESC);
ALTER TABLE orgs ADD COLUMN slug_prefix TEXT;
UPDATE orgs SET slug_prefix = '' WHERE id = 'org-demo';
ALTER TABLE buildings ADD COLUMN display_code TEXT;
UPDATE buildings SET display_code = code WHERE display_code IS NULL;
